### ISSUE TITLE
already parsed request body detected, having upstream middleware parser is not recommended

### ISSUE THREAD

**Issue by patrykkopycinski** [OpusCapita/auth#19]
resolving to use req.body or request.body instead

**Comment by sureshvarman-cronj** [comment]
https://github.com/panva/node-oidc-provider/issues/22#issuecomment-265999690

Now web-init already has body parser by itself, we cannot avoid that warning since the koa for node oidc and web-init are using parser individually, anyway this is not making any issues in parsing the body. so closing for now, can be reopened at any time.
