### ISSUE TITLE
settings.config.findById uses ServiceClient wrongly

### ISSUE THREAD

**Issue by kwierchris** [OpusCapita/auth#25]
As ServiceClient is used here in order to request a user from the User service, it has to provide request headers in order to correctly call the User service. [Look here](https://github.com/OpusCapita/auth/blob/develop/src/server/index.js#L52)

The current implementation only works because the User service is not yet secured using things like auth headers. The best was is to forward incoming request headers using the [.contextify](https://github.com/OpusCapitaBusinessNetwork/service-client/wiki#serviceclientcontextify) function of ServiceClient with the *headers* property of an express request (req.headers).
This means, that the call has to be done inside the express request context.

E.g.
```JS
app.get('/', (req, res)
{
    ...
    client.contextify({ headers : req.headers });
    client.get(...)
    ...
})
```

**Comment by sureshvarman-cronj** [comment]
There is no authentication checks on any individual services so far, eventually i feel like there should not be any internal calls itself, eventhough we call them internal call, it should go via gateway, since we are going to have ACL checks and IdToken check which is already in place on the gateway level, it is better to happen via kong, if i'm not wrong. The above fix is for demo.

**Comment by kwierchris** [comment]
If we would route all the "internal" calls through the whole infrastructure we would add a lot of overhead to each of these services calls.
